/* ========================================================================== *
 * Copyright 2014 USRZ.com and Pier Paolo Fumagalli                           *
 * -------------------------------------------------------------------------- *
 * Licensed under the Apache License, Version 2.0 (the "License");            *
 * you may not use this file except in compliance with the License.           *
 * You may obtain a copy of the License at                                    *
 *                                                                            *
 *  http://www.apache.org/licenses/LICENSE-2.0                                *
 *                                                                            *
 * Unless required by applicable law or agreed to in writing, software        *
 * distributed under the License is distributed on an "AS IS" BASIS,          *
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.   *
 * See the License for the specific language governing permissions and        *
 * limitations under the License.                                             *
 * ========================================================================== */
package org.usrz.libs.crypto.utils;

import java.security.KeyPair;
import java.security.KeyPairGenerator;
import java.security.NoSuchAlgorithmException;

/**
 * Build a {@link KeyPair}.
 *
 * @author <a href="mailto:pier@usrz.com">Pier Fumagalli</a>
 */
public class KeyPairBuilder {

    private String algorithm = "RSA";
    private int keySize = 1024;

    /**
     * Create a new {@link KeyPairBuilder} using the default <em>RSA</em>
     * algorithm and producing keys of 1024 bits.
     */
    public KeyPairBuilder() {
        /* Nothing to do, initialized to sensible defaults */
    }

    /**
     * Create a new {@link KeyPairBuilder} with the specified algorithm
     * and producing keys of 1024 bits.
     *
     * @see #algorithm(String)
     */
    public KeyPairBuilder(String algorithm) {
        algorithm(algorithm);
    }

    /**
     * Generate and return a new {@link KeyPair}.
     */
    public KeyPair build() {
        final KeyPairGenerator generator;
        try {
            generator = KeyPairGenerator.getInstance(algorithm);
        } catch (NoSuchAlgorithmException exception) {
            throw new IllegalStateException("Algoritmh \"" + algorithm + "\" not supported", exception);
        }
        generator.initialize(keySize);
        return generator.generateKeyPair();
    }

    /**
     * Specify the name of the algorithm used by this {@link KeyPairBuilder}.
     */
    public KeyPairBuilder algorithm(String algorithm) {
        if (algorithm == null) throw new NullPointerException("Null algorithm");
        this.algorithm = algorithm;
        return this;
    }

    /**
     * Specify the size (in bits) of the keys generated by this
     * {@link KeyPairBuilder}.
     */
    public KeyPairBuilder keySize(int keySize) {
        if (keySize < 0) throw new IllegalArgumentException("Invalid key size " + keySize);
        this.keySize = keySize;
        return this;
    }
}
